# Generated by Django 2.2.5 on 2022-05-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero',
            old_name='genero',
            new_name='a',
        ),
    ]
