# Generated by Django 2.2.5 on 2022-05-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220502_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
